"use client";
import {ArrowRight,BookOpen,CheckCircle2,Clock3,ShieldCheck,Star} from "lucide-react";

function LikaLogo(){return <div className="brand"><div className="brand-mark">🦘</div><span>APLIKA</span></div>}

export default function Home(){
 const go=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"});
 return <main>
  <header><div className="container nav"><LikaLogo/><nav className="navlinks"><a href="#como">Cómo funciona</a><a href="#practica">Práctica</a><a href="#precio">Premium</a><a href="#faq">FAQ</a></nav><div className="actions"><button className="btn btn-outline" onClick={()=>alert("El acceso se activará al conectar la autenticación de APLIKA.")}>Iniciar sesión</button><button className="btn btn-primary" onClick={()=>go("practica")}>Empezar</button></div></div></header>
  <section className="hero"><div className="container hero-grid"><div><span className="eyebrow">🦘 APLIKA · Permiso B</span><h1>Aprende. Practica.<br/><span>APLIKA.</span></h1><p>Una plataforma pensada para preparar el teórico de conducir con exámenes, práctica por temas y seguimiento de tu progreso.</p><div className="hero-actions"><button className="btn btn-yellow" onClick={()=>go("practica")}>Probar gratis <ArrowRight size={17}/></button><button className="btn btn-outline" onClick={()=>go("como")}>Ver cómo funciona</button></div><div className="hero-note">Empieza con una prueba gratuita de 15 preguntas.</div></div><div className="lika-wrap"><div className="circle"><div className="lika" aria-label="Lika, mascota de APLIKA">🦘</div></div><div className="tag">Lika <small>tu compañera de estudio</small></div></div></div></section>
  <section id="como" className="section"><div className="container"><div className="section-head"><h2>Todo lo que necesitas para prepararte</h2><p>La experiencia de APLIKA está pensada para que puedas estudiar desde ordenador, móvil o tablet.</p></div><div className="cards"><Feature icon={<BookOpen/>} title="Exámenes de 30 preguntas" text="Practica con una experiencia estructurada como un examen teórico real."/><Feature icon={<Clock3/>} title="Controla tu tiempo" text="Entrena con tiempo limitado y aprende a gestionar cada pregunta."/><Feature icon={<CheckCircle2/>} title="Revisa tus errores" text="Consulta tus respuestas, detecta tus fallos y vuelve a practicar lo que necesitas."/><Feature icon={<Star/>} title="Práctica por temas" text="Trabaja cada bloque y sigue tu porcentaje de dominio."/><Feature icon={<ShieldCheck/>} title="Tu progreso, privado" text="Tu cuenta guarda únicamente la información necesaria para tu progreso y tus exámenes."/><Feature icon={<ArrowRight/>} title="Mis Exámenes" text="Consulta tu historial, notas, resultados y revisa cada examen realizado." /></div></div></section>
  <section id="practica" className="section" style={{paddingTop:10}}><div className="container"><div className="exam"><div><h2>Empieza con 15 preguntas gratis</h2><p>Una primera toma de contacto para conocer APLIKA antes de acceder a toda la plataforma.</p><button className="btn btn-yellow" onClick={()=>alert("El motor de preguntas se conectará a Supabase en el siguiente paso.")}>Empezar prueba <ArrowRight size={16}/></button></div><div className="stats"><div className="stat"><strong>15</strong><span>preguntas</span></div><div className="stat"><strong>30</strong><span>preguntas PRO</span></div></div></div></div></section>
  <section id="precio" className="section"><div className="container"><div className="section-head"><h2>Una sola compra</h2><p>Sin suscripciones. El acceso Premium de APLIKA está planteado como un pago único con acceso permanente.</p></div><div className="pricing"><div className="price"><h3>Gratis</h3><strong>0€</strong><ul><li>Prueba inicial de 15 preguntas</li><li>Experiencia APLIKA</li></ul><button className="btn btn-outline" onClick={()=>go("practica")}>Probar gratis</button></div><div className="price pro"><h3>APLIKA Premium</h3><strong>Próximamente</strong><ul><li>Exámenes completos de 30 preguntas</li><li>Práctica por temas</li><li>Preguntas falladas</li><li>Historial de exámenes</li><li>Seguimiento del progreso</li></ul><button className="btn btn-primary" onClick={()=>alert("El pago se habilitará al integrar Stripe.")}>Acceder a Premium</button></div></div></div></section>
  <section id="faq" className="section" style={{paddingTop:20}}><div className="container"><div className="section-head"><h2>Preguntas frecuentes</h2><p><b>¿Es APLIKA una autoescuela?</b> No. Es una plataforma de preparación. <br/><br/><b>¿Dónde se guardará mi progreso?</b> En tu cuenta, mediante la infraestructura segura de APLIKA.</p></div></div></section>
  <footer className="footer"><div className="container footer-grid"><div><LikaLogo/><p>APLIKA · Aprende. Practica. APLIKA.</p></div><div className="footer-links"><span>Privacidad</span><span>Cookies</span><span>Aviso legal</span><span>Contacto</span></div></div></footer>
 </main>
}
function Feature({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <article className="card"><div className="icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>}